# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9e0684f1e0cc670b241d50fe0a6bce9b103465ddc94faec48b0cddd2431725e31dbd3f4f787529dbec8ffe196c0f83ad8af74262145ea5a9249f6ebef2d722

test:
  secret_key_base: b3b70e2ed8776bb09b37a990b728455712a3ad952a785f9719b6f2105637c44ee2354a52e4462e801003e8abca70e78e999901c9748d56759d32bed07886e16f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
